# Generated by Django 2.2.6 on 2019-11-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertex',
            name='end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end', to='graphgame.Edge'),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='start', to='graphgame.Edge'),
        ),
    ]
