# Generated by Django 2.2.6 on 2019-11-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphgame', '0003_auto_20191109_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vertex',
            name='end',
        ),
        migrations.RemoveField(
            model_name='vertex',
            name='start',
        ),
        migrations.AddField(
            model_name='edge',
            name='end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ends', to='graphgame.Vertex'),
        ),
        migrations.AddField(
            model_name='edge',
            name='start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starts', to='graphgame.Vertex'),
        ),
    ]
