# Generated by Django 2.2.6 on 2019-11-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphgame', '0004_auto_20191109_2050'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vertex',
            constraint=models.UniqueConstraint(fields=('x', 'y'), name='pair of coords'),
        ),
    ]
